#server:
#  port: 8080
#  
#  
#spring:
#   datasource:
#    url: jdbc:postgresql://localhost:5432/hotleServiceDb
#    username: adempiere
#    password: postgres
#    
#
# 
# 
#jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: true
#      
#      
#      spring:
#      datasource:
#      driver-class-name: org.postgresql.Driver